### PR TITLE
Feature/account created data export

### PR DESCRIPTION
**Pull request by markmcavoy**
I've added the ability to export the user's created on date into the CSV file. 
Screenshot 2021-10-06 123415

### CODE REVIEW

**Comment by fordnn** [comment]
Hi Mark,

Thank you very much for your contribution! I will include this into the next release.

Best regards,
Serg

**Comment by markmcavoy** [comment]
Hi Serg

Thank you, your module is really useful. Happy to contribute. 

Regards

Mark

**Review by fordnn — COMMENTED** [review]
Sorry, but GetPortalRoles is Deprecated in DNN 7.3. We have to use GetRoles instead.

**Review by fordnn — APPROVED** [review]

**Review by fordnn — APPROVED** [review]

**Comment by fordnn** [comment]
Hi Mark!

Thank you again for your contribution. It has been merged and included into the PA 01.02.07.

Best regards,
Serg

**Comment by markmcavoy** [comment]
Hi Serg

Thank you!

Your tool is very useful, so thank you for contributing it back to the
community.

Regards

Mark

**Pull request merged**
